name: Hotel Sys Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and build
        working-directory: ${{ github.workspace }}/hotelsys-demo
        run: npm install && npm run build && cp dist/hotelsys/index.html dist/hotelsys/404.html
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: hotelsys-demo/dist/hotelsys # The folder the action should deploy.        